import ContactForm from "@/components/contactForm/ContactForm";
import React from "react";

export const metadata = {
	title: "ArtEclat-Contact",
	description: "Generated by create next app",
};

const Contact = () => {
	return (
		<div>
			<ContactForm />
		</div>
	);
};

export default Contact;
